# Generated by Django 4.2.6 on 2023-11-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_especie', models.CharField(max_length=150)),
                ('imagem', models.ImageField(upload_to='especies/%y/%m/%d')),
                ('introducao', models.TextField()),
                ('origem', models.TextField()),
                ('causa_efeito', models.TextField()),
                ('prevencao', models.TextField()),
            ],
        ),
    ]
