# Generated by Django 4.2.6 on 2023-12-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especies',
            name='display_type',
            field=models.CharField(choices=[('cards', 'Cards'), ('list', 'Listagem')], default='cards', max_length=5),
        ),
    ]
